# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField()),
                ('browsing', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
                ('leeftijd', models.IntegerField()),
                ('contactmoment', models.CharField(max_length=30)),
                ('lopend', models.CharField(max_length=30)),
                ('browsing', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Regeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
            ],
        ),
    ]
