# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_regeling_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persoon',
            name='contactmoment',
        ),
        migrations.AddField(
            model_name='persoon',
            name='contactmomenten',
            field=models.ManyToManyField(null=True, related_name='contact_reg', to='simple.Regeling'),
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='browsing',
        ),
        migrations.AddField(
            model_name='persoon',
            name='browsing',
            field=models.ManyToManyField(null=True, related_name='browsing_reg', to='simple.Regeling'),
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='lopend',
        ),
        migrations.AddField(
            model_name='persoon',
            name='lopend',
            field=models.ManyToManyField(null=True, related_name='lopend_reg', to='simple.Regeling'),
        ),
    ]
