# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_auto_20171028_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='browsing',
        ),
        migrations.AddField(
            model_name='ip',
            name='browsing',
            field=models.ManyToManyField(related_name='ip_reg', to='simple.Regeling'),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='browsing',
            field=models.ManyToManyField(related_name='browsing_reg', to='simple.Regeling'),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='contactmomenten',
            field=models.ManyToManyField(related_name='contact_reg', to='simple.Regeling'),
        ),
        migrations.AlterField(
            model_name='persoon',
            name='lopend',
            field=models.ManyToManyField(related_name='lopend_reg', to='simple.Regeling'),
        ),
    ]
