# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_auto_20171028_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vragen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('qnumber', models.IntegerField()),
                ('question', models.CharField(max_length=300)),
                ('dependendOn', models.IntegerField()),
                ('dependendOnValue', models.BooleanField()),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='persoon',
            old_name='lopend',
            new_name='regelingen',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='browsing',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='contactmomenten',
        ),
        migrations.AddField(
            model_name='persoon',
            name='ontslagaanvraag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persoon',
            name='werkend',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regeling',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='vragen',
            name='regeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Regeling'),
        ),
    ]
