# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0005_auto_20171028_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regeling',
            new_name='RegelingOpties',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='browsing',
        ),
        migrations.RemoveField(
            model_name='vragen',
            name='regeling',
        ),
        migrations.DeleteModel(
            name='IP',
        ),
        migrations.DeleteModel(
            name='Vragen',
        ),
    ]
