# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0007_persoon_geslacht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regelingen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
                ('update_url', models.CharField(max_length=100)),
                ('insert_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RegelingOpties',
        ),
        migrations.AlterField(
            model_name='persoon',
            name='regelingen',
            field=models.ManyToManyField(related_name='lopend_reg', to='simple.Regelingen'),
        ),
    ]
