# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0008_auto_20171028_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='regelingen',
            name='info_url',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
